services:
  flask-app:
    build:
      context: ./assignment_1_flask_app
      dockerfile: Dockerfile
    image: uwschriss/assignment_1_flask_app:latest
    # The app is only accessible via Nginx.

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app



  